name: Run workflow on push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [22]

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
        ports:
          - 3307:3307

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java}}

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for MySQL
        run: |
          for i in {30..0}; do
            if echo 'SELECT 1' | mysql -h 127.0.0.1 -P 3307 -u springuser -p ${{secrets.MYSQL_ROOT_PASSWORD}} mylibrary &> /dev/null; then
              break
            fi
            echo 'MySQL init process in progress...'
            sleep 1
          done

      - name: Install dependencies
        run: mvn install -DskipTests=true

      - name: Run tests
        run: mvn clean package

      - name: Verify build
        run: mvn verify
